url: http://reeshuffled.github.io
baseurl: ""
title: "Rees Writes"
author: "Rees Draminski"
description: "Where I blog about my various interests and things that I am working on."
permalink: /:categories/:title/
timezone: "America/New_York"
plugins:
  - jekyll-include-cache