import argparse
import json
import os
import re
from datetime import datetime
from pathlib import Path
from urllib.parse import parse_qs, urlparse

# oyaml is a drop-in replacement for PyYAML which preserves dict ordering
# import before everything so python-frontmatter uses oyaml
import frontmatter

import requests
from bs4 import BeautifulSoup
from git_tools import get_publish_date

draft_directory = "_drafts"
post_directory = "_posts"

# Map from URL path segment (the page name in /data/<page>) to the embed.py type prefix.
# These must exactly match the item ids generated by the data pages' Liquid templates.
CITABLE_PAGES: dict[str, str] = {
    "movies": "movie",
    "books-read": "book",
    "tv": "tv",
}

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    )
}


def prompt(message):
    response = input(message)

    if response.strip() == "":
        print("Response cannot be empty. Please try again.")

        return prompt(message)

    return response


def create_draft(args: argparse.Namespace):
    title = args.title or prompt("Title: ")
    slug = args.slug or title.lower().replace(" ", "-")

    filename = title.replace(" ", "-") + ".md"
    file_path = os.path.join(draft_directory, filename)
    if os.path.isfile(file_path):
        print(
            f"Draft with filename '{filename}' already exists. Please choose a different title."
        )

        return create_draft(args)

    with open(file_path, "w") as f:
        f.write(
            frontmatter.dumps(
                frontmatter.Post(
                    layout="post",
                    type="stub",
                    tags=[],
                    title=title,
                    slug=slug,
                    description="",
                    content="",
                )
            )
        )

    # open new draft file in VSCode
    os.system(f"code {file_path}")


def _build_citation_title_map() -> dict[str, str]:
    """
    Build a lookup map from '<page>:<item_id>' to display title for all citable media pages.

    The item_id matches the Liquid-template `?item=` value used on each data page:
      - movies:   tmdb_id (as string) or "name|year"
      - books-read: isbn13 or isbn or title
      - tv:       tmdb_id (as string) or title
    """
    result: dict[str, str] = {}

    movies_path = Path("_data/media/movies.json")
    if movies_path.exists():
        data = json.loads(movies_path.read_text())
        for m in data.get("watched", []):
            tmdb_id = m.get("tmdb_id")
            item_id = (
                str(tmdb_id) if tmdb_id else f"{m.get('name', '')}|{m.get('year', '')}"
            )
            result[f"movies:{item_id}"] = m.get("name", "")

    books_path = Path("_data/media/books.json")
    if books_path.exists():
        data = json.loads(books_path.read_text())
        for b in data.get("read", []):
            item_id = str(b.get("isbn13") or b.get("isbn") or b.get("title", ""))
            if item_id:
                result[f"books-read:{item_id}"] = b.get("title", "")

    tv_path = Path("_data/media/tv.json")
    if tv_path.exists():
        data = json.loads(tv_path.read_text())
        for s in data.get("shows", []):
            tmdb_id = s.get("tmdb_id")
            item_id = str(tmdb_id) if tmdb_id else s.get("title", "")
            if item_id:
                result[f"tv:{item_id}"] = s.get("title", "")

    return result


def extract_citations(post_filepath: str, _title_map: dict | None = None) -> list[dict]:
    """
    Scan a Jekyll post for data-citation links (/data/<page>?item=<id> or /inventory/…?item=<id>)
    and return a list of {url, title, type, id} dicts.

    This is a lightweight scan — no HTTP fetches, no frontmatter loading.
    It is used to backfill citations onto posts that already have links.internal/external.
    """
    if _title_map is None:
        _title_map = _build_citation_title_map()

    with open(post_filepath, "r", encoding="utf-8") as f:
        content = f.read()

    md_link_re = re.compile(
        r"(?<!!)\[(?P<text>[^\]]*)\]\((?P<target>[^)]+)\)"
        r"|"
        r'<a\s[^>]*href=["\'](?P<href>[^"\']+)["\'][^>]*>',
        re.IGNORECASE | re.DOTALL,
    )

    # type → page name (inverse of CITABLE_PAGES)
    _type_to_page = {v: k for k, v in CITABLE_PAGES.items()}

    citations: list[dict] = []

    def _add(item_type: str, item_id: str) -> None:
        page = _type_to_page.get(item_type)
        if not page:
            return
        url = f"/data/{page}?item={item_id}"
        title = _title_map.get(f"{page}:{item_id}", "")
        citations.append({"url": url, "title": title, "type": item_type, "id": item_id})

    for match in md_link_re.finditer(content):
        raw_target = match.group("target") or match.group("href")
        if not raw_target:
            continue
        target = raw_target.strip()
        if not (target.startswith("/data/") or target.startswith("/inventory/")):
            continue

        parsed = urlparse(target)
        parts = parsed.path.strip("/").split("/")
        # parts[0] = "data" or "inventory", parts[1] = page name
        if len(parts) < 2:
            continue
        page = parts[1]
        if page not in CITABLE_PAGES:
            continue
        qs = parse_qs(parsed.query)
        item_ids = qs.get("item", [])
        if not item_ids:
            continue
        _add(CITABLE_PAGES[page], item_ids[0])

    # Also pick up {% include media-citation-card.html type="..." id="..." %}
    mcc_re = re.compile(
        r"""\{%-?\s+include\s+media-citation-card\.html\s+[^%]*?"""
        r"""type=['"]([\w]+)['"]\s+id=['"]([\w.X]+)['"][^%]*?-?%\}""",
        re.IGNORECASE,
    )
    for m in mcc_re.finditer(content):
        _add(m.group(1), m.group(2))

    return citations


def extract_links(post_filepath: str) -> dict:
    """
    Parse a Jekyll post and return internal, external, and data-citation links.

    Args:
        post_filepath: Path to the Jekyll post .md file

    Returns:
        dict with keys 'internal', 'external', and 'citations':
          - internal: list of {'url': ..., 'title': ...} for {% post_url %} links
          - external: list of {'url': ..., 'title': ...} for http(s) links
          - citations: list of {'url': ..., 'title': ..., 'type': ..., 'id': ...}
                       for /data/<page>?item=<id> and /inventory/<page>?item=<id> links
    """
    post_filepath = Path(post_filepath)
    posts_dir = post_filepath.parent  # assumes siblings live in the same _posts/ dir

    with open(post_filepath, "r", encoding="utf-8") as f:
        content = f.read()

    # Match ALL markdown links: [text](target)
    # target is either a normal URL or a Jekyll {% post_url slug %} tag
    # images are ![alt](url), so a negative lookbehind on ! excludes that
    md_link_re = re.compile(
        r"(?<!!)\[(?P<text>[^\]]*)\]\((?P<target>[^)]+)\)"  # [text](target)
        r"|"
        r'<a\s[^>]*href=["\'](?P<href>[^"\']+)["\'][^>]*>'  # <a href="...">
        r"(?P<atag_text>.*?)"
        r"</a>",
        re.IGNORECASE | re.DOTALL,
    )

    internal_links: list[dict] = []
    external_links: list[dict] = []
    citations: list[dict] = []

    title_map = _build_citation_title_map()

    for match in md_link_re.finditer(content):
        target = (match.group("target") or match.group("href")).strip()

        # ── Internal: {% post_url some-slug %} ──────────────────────────────
        post_url_re = re.match(
            r"\{%\s*post_url\s+(?P<post_file_name>\S+)\s*%\}", target
        )
        if post_url_re:
            post_file_name = post_url_re.group("post_file_name")
            candidate = posts_dir / f"{post_file_name}.md"

            title = ""
            slug = ""

            try:
                linked_post = frontmatter.load(str(candidate))
                title = linked_post.get("title", "")
                slug = linked_post.get("slug", "")
            except Exception as exc:
                print(
                    "Dead post_url reference '%s' in %s: %s",
                    post_file_name,
                    post_filepath,
                    exc,
                )
            internal_links.append({"url": f"/posts/{slug}", "title": title})

        # ── Data citation: /data/<page>?item=<id> or /inventory/<page>?item=<id> ──
        elif target.startswith("/data/") or target.startswith("/inventory/"):
            parsed = urlparse(target)
            parts = parsed.path.strip("/").split("/")
            # parts[0] = "data" or "inventory", parts[1] = page name
            if len(parts) >= 2:
                page = parts[1]
                qs = parse_qs(parsed.query)
                item_ids = qs.get("item", [])
                if item_ids and page in CITABLE_PAGES:
                    item_id = item_ids[0]
                    item_type = CITABLE_PAGES[page]
                    item_title = title_map.get(f"{page}:{item_id}", "")
                    citations.append(
                        {
                            "url": target,
                            "title": item_title,
                            "type": item_type,
                            "id": item_id,
                        }
                    )

        # ── External: normal http(s) URL ────────────────────────────────────
        elif target.startswith("http://") or target.startswith("https://"):
            title = ""
            try:
                resp = requests.get(target, timeout=10, headers=HEADERS)
                resp.raise_for_status()

                soup = BeautifulSoup(resp.text, "html.parser")
                title_tag = soup.find("title")
                title = title_tag.get_text(strip=True) if title_tag else ""
            except Exception as exc:
                print(
                    "Failed to fetch external URL '%s' in %s: %s",
                    target,
                    post_filepath,
                    exc,
                )
            external_links.append({"url": target, "title": title})

    return {
        "internal": internal_links,
        "external": external_links,
        "citations": citations,
    }


def enrich_frontmatter(args: argparse.Namespace):
    # inspired by: https://landscapearchaeology.org/2019/frontmatter/
    for file_name in os.listdir(post_directory):
        # get file path to post within post directory
        file_path = os.path.join(post_directory, file_name)

        # check if object is nested subfolder, if so, skip
        if not os.path.isfile(file_path):
            continue

        # load post with python-frontmatter
        post = frontmatter.load(file_path)

        # get post year from file name
        post_date_start_index = file_path.rindex("/") + 1
        post_year = file_path[post_date_start_index : post_date_start_index + 4]

        # add post year as tag if not already present
        if post_year not in post.metadata["tags"]:
            post.metadata["tags"].append(post_year)

        # add publish datetime to frontmatter if not already present
        if "publish_datetime" not in post.metadata:
            publish_date = get_publish_date(file_path)

            # may not be published yet, so only add publish_datetime if we were able to get it from git history
            if publish_date:
                post.metadata["publish_datetime"] = publish_date

        # add links to frontmatter if not already present
        if "links" not in post.metadata:
            post.metadata["links"] = extract_links(file_path)
        elif "citations" not in (post.metadata.get("links") or {}):
            # Post already has internal/external links but predates citations —
            # backfill citations only (lightweight scan, no HTTP fetches).
            post.metadata["links"]["citations"] = extract_citations(file_path)
        elif not (post.metadata.get("links") or {}).get("citations"):
            # Citations key exists but is empty — check if body has media-citation-card
            # includes that should be registered (without rewriting posts that have no cites).
            found = extract_citations(file_path)
            if found:
                post.metadata["links"]["citations"] = found

        # write post back to file with updated frontmatter
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(frontmatter.dumps(post))


def promote_draft(args: argparse.Namespace):
    # get list of drafts in alphabetical order
    draft_files = sorted(
        [
            f
            for f in os.listdir(draft_directory)
            if os.path.isfile(os.path.join(draft_directory, f))
        ]
    )
    # print all drafts with their titles and prompt user to select one by number
    for i, file_name in enumerate(draft_files):
        file_path = os.path.join(draft_directory, file_name)

        if os.path.isfile(file_path):
            draft = frontmatter.load(file_path)

            print(f"{i + 1}. {draft['title']}")

    # prompt user to select draft by number and validate input
    choice = int(prompt("Enter your choice: "))
    if choice < 1 or choice > len(draft_files):
        print("Invalid choice. Please try again.")

        return promote_draft()

    # get publish date as ISO string and rename draft file to post file path to promote draft to post
    publish_date = datetime.today().strftime("%Y-%m-%d")
    draft_file_path = os.path.join(draft_directory, draft_files[choice - 1])
    post_file_path = os.path.join(
        post_directory, publish_date + "-" + draft_file_path.split("/")[-1]
    )

    print(f"Promoting draft '{draft_file_path}' to post '{post_file_path}'...")

    # check if post file path already exists
    if os.path.isfile(post_file_path):
        print(f"Post with filename '{post_file_path}' already exists.")

        return promote_draft()

    # rename draft file to post file path to promote draft to post
    os.rename(draft_file_path, post_file_path)

    # open new post file in VSCode
    os.system(f"code {post_file_path}")
